import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";
import { Noto_Serif_KR } from "next/font/google";

const notoSerifSans = Noto_Serif_KR({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app!!!!!",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={notoSerifSans.className}>
        <nav className='bg-orange-600 space-x-6'>
          <Link href='/'>Home</Link>
          <Link href='/products'>products</Link>
          <Link href='/about'>about</Link>
          <Link href='/contact'>contact</Link>
        </nav>
        <main className='h-full'>{children}</main>
      </body>
    </html>
  );
}
